fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    exclude: (terraform/|charts/)
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-json
    exclude: (.vscode/)
  - id: mixed-line-ending
    args: ['--fix=lf']
    description: Forces to replace line ending by the UNIX 'lf' character.
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    args: [--diff, --check]

- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v3.0.0a5
  hooks:
  - id: pylint
    args: [--disable=all, --enable=unused-import]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
  - id: mypy
    exclude: (tests/|archived/)
    args: [--strict]

- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
